[font]
size = 12.0

[font.normal]
#family = "FiraCode Nerd Font"
style = "Regular"
family = "JetBrainsMonoNL Nerd Font" # for oh my zsh + powerlevel10k

[window]
opacity = 0.95

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/zsh"

#[colors.primary]
#background = "#0A1B2F"


[colors.primary]
#background = '#191724'
background = '#121017'
foreground = '#e0def4'

[colors.cursor]
text = '#e0def4'
cursor = '#524f67'

[colors.vi_mode_cursor]
text = '#e0def4'
cursor = '#524f67'

[colors.selection]
text = '#e0def4'
background = '#403d52'

[colors.normal]
black = '#26233a'
red = '#eb6f92'
green = '#31748f'
yellow = '#f6c177'
blue = '#9ccfd8'
magenta = '#c4a7e7'
cyan = '#ebbcba'
white = '#e0def4'

[colors.bright]
black = '#6e6a86'
red = '#eb6f92'
green = '#31748f'
yellow = '#f6c177'
blue = '#9ccfd8'
magenta = '#c4a7e7'
cyan = '#ebbcba'
white = '#e0def4'

[colors.hints]
start = {foreground = '#908caa', background = '#1f1d2e' }
end = { foreground = '#6e6a86', background = '#1f1d2e' }

[terminal]
